### ISSUE TITLE
Implement trace storing convention

### ISSUE THREAD

**Issue by fabiansinz** [cajal/pipeline#115]
Because Matlab cannot store 1d arrays (in a Python sense) python has to deal with 2d arrays anyway, so we got with Matlab column major convention here: All trace should be stored as 
- **column arrays**
- **single** unless there is an important reason to store them as double. 

@dimitri-yatsenko will write a script that converts existing traces to the correct format.

**Comment by dimitri-yatsenko** [comment]
closing?

**Comment by fabiansinz** [comment]
What pull request solved that?

**Comment by dimitri-yatsenko** [comment]
Are all new traces stored as float32 columns?
