### ISSUE TITLE
Debug NaNs at end of motion correction traces

### ISSUE THREAD

**Issue by jakereimer** [cajal/pipeline#118]
NaNs at the beginning of the trace are due to PMT blanking. The frame there is dark, so motion correction cannot occur and nans are recorded for the movement trace. The PMT is reset by the experimenter before the visual stimulus begins, so this should not have an effect on any analysis. However, NaNs later in the scan are not expected. Currently, scans have a variable but large number (several thousand) of NaN'ed frames at the end of the file. This may because of an error in motion correction or in Reader5.

**Comment by dimitri-yatsenko** [comment]
The problem is not due to motion correction but a bug in `ne7.scanimage.Reader5`.  More specifically, `frames_per_file` is computed incorrectly.

Fixed the problem.  Need to repopulate all data.

**Comment by dimitri-yatsenko** [comment]
The problem is fixed.  Some nans still occur when the frames go dark below 25% of the template brightness.
