### ISSUE TITLE
Write helper functions to load stimuli and spikes

### ISSUE THREAD

**Issue by fabiansinz** [cajal/pipeline#119]
... to take the pain out of synchronization.

**Comment by dimitri-yatsenko** [comment]
What is the exact problem?

**Comment by jakereimer** [comment]
Something that immediately returns the frame indices for a particular trial would be useful.

**Comment by fabiansinz** [comment]
Sync and Trial magic is hard to understand for newbies. Maybe a helper function that spits out indices into the traces/recordings where particular stimuli were presented would be helpful.

**Comment by dimitri-yatsenko** [comment]
The scripts in `prepare_monet.m` and `prepare_madmax.m` show examples of how to do this. You can use this as the starting point.

**Comment by jakereimer** [comment]
Oh, actually if we want to be really slick, we should write a helper function that returns adjusted frame times for each cell trace depending on the mask's position in the imaging frame. If we're imaging at 10-15 Hz, this adjustment could be up to ~90ms or so, which is certainly a relevant time scale for relating calcium traces to stimuli. Could make the change in RF strength at different lags even more precise for example.

**Comment by ecobost** [comment]
there is stimline.tune.TraceMixin.load_traces_and_frametimes that does this
