### ISSUE TITLE
Propose to not infer name of behaviorfile

### ISSUE THREAD

**Issue by fabiansinz** [cajal/pipeline#133]
Currently, the file with the sync information is inferred from the scan file. This is prone for errors. I propose that the experimenter always has to enter the filename for the h5 file.

**Comment by dimitri-yatsenko** [comment]
It irks me that we use the file format `hd5` to identify the file.  The file or files should have a name that describes its contents and function, not the format.

**Comment by jakereimer** [comment]
I don't really agree that making someone enter a second filename will reduce errors, but within a couple months we should be automating the entry of this information anyway, so I am fine with this change if it seems necessary.
