### ISSUE TITLE
RF Map size too big ! Switch to uint8

### ISSUE THREAD

**Issue by olakiril** [cajal/pipeline#152]

**Comment by fabiansinz** [comment]
Could you please add more details? I have no idea what you are talking about.

**Comment by dimitri-yatsenko** [comment]
I guess it's about the fact that I saved RF maps in floats.  The RF Maps 256 x 144 x 6 for each cell and each processing method, which will translate into gigabytes of maps per experiment.  By switching from float32 to int8, we can reduce the size by 75%.
