### ISSUE TITLE
`cvxopt` not installed

### ISSUE THREAD

**Issue by fabiansinz** [cajal/pipeline#227]
When starting population for `ExtractRaw` I get the warning that `cvxopt` is not installed. The Dockerfile needs to be changed at the part where CaImAn is installed and the installation of `cvxopt` needs to be added there. Maybe we can check their Dockerfile.

**Comment by ecobost** [comment]
Fixed in newer versions of CaImAn. Also we use a different optimizer (cvxpy) which was added to the Dockerfile in #229
