### ISSUE TITLE
Components in ExtractRaw

### ISSUE THREAD

**Issue by fabiansinz** [cajal/pipeline#231]
When manually classifying the segmentation masks, I noticed that each slice contains 2 large masks. Could it be that the background masks have been inserted along with the normal masks?

```{'animal_id':12690, 'session':1, scan_idx:'12'}```

**Comment by ecobost** [comment]
When running cnmf I ask for 4 background components and they are all in the background components matrix, plus they have each pixel in the image defined so they look different to any mask in the normal components. I think the big mask in the normal components probably comes by merging many bad components together and represent something like overall activation of that part of the tissue.

This is what I checked:
```python
i=0
activity, masks = (preprocess.ExtractRaw.BackgroundComponents() & key & {'channel': 1, 'slice': 1}).fetch1['activity', 'masks']
plt.imshow(masks[:,:,i]) # loop over i, plotting the 4 background components looks like they should

# compare it with the big mask
masks = (preprocess.ExtractRaw.BackgroundComponents() & key & {'channel': 1, 'slice': 1}).get_all_masks()
plt.imshow(masks[:,:,62]) # 62 is the mask with the highest number of defined pixels

```
