### ISSUE TITLE
Implement function that returns the correct `frame_times` for a given field in `meso`

### ISSUE THREAD

**Issue by fabiansinz** [cajal/pipeline#274]
For `reso` we were able to use `frame_times[slice-1::nslices]`. However, in `meso` some ROIs might be scanned, others might not (according to @olakiril). That makes the correct extraction of the time shift difficult and error prone for people who do not know about it. Can we write a function that returns the correct `frame_times`?

**Comment by ecobost** [comment]
stimline.TraceMixin.load_traces_and_frametimes does this
